// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v5.29.3
// source: transport/internet/headers/srtp/config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { messageTypeRegistry } from "../../../../typeRegistry";

export const protobufPackage = "xray.transport.internet.headers.srtp";

export interface Config {
  $type: "xray.transport.internet.headers.srtp.Config";
  version: number;
  padding: boolean;
  extension: boolean;
  csrcCount: number;
  marker: boolean;
  payloadType: number;
}

function createBaseConfig(): Config {
  return {
    $type: "xray.transport.internet.headers.srtp.Config",
    version: 0,
    padding: false,
    extension: false,
    csrcCount: 0,
    marker: false,
    payloadType: 0,
  };
}

export const Config: MessageFns<Config, "xray.transport.internet.headers.srtp.Config"> = {
  $type: "xray.transport.internet.headers.srtp.Config" as const,

  encode(message: Config, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version !== 0) {
      writer.uint32(8).uint32(message.version);
    }
    if (message.padding !== false) {
      writer.uint32(16).bool(message.padding);
    }
    if (message.extension !== false) {
      writer.uint32(24).bool(message.extension);
    }
    if (message.csrcCount !== 0) {
      writer.uint32(32).uint32(message.csrcCount);
    }
    if (message.marker !== false) {
      writer.uint32(40).bool(message.marker);
    }
    if (message.payloadType !== 0) {
      writer.uint32(48).uint32(message.payloadType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Config {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.version = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.padding = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.extension = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.csrcCount = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.marker = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.payloadType = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Config {
    return {
      $type: Config.$type,
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      padding: isSet(object.padding) ? globalThis.Boolean(object.padding) : false,
      extension: isSet(object.extension) ? globalThis.Boolean(object.extension) : false,
      csrcCount: isSet(object.csrcCount) ? globalThis.Number(object.csrcCount) : 0,
      marker: isSet(object.marker) ? globalThis.Boolean(object.marker) : false,
      payloadType: isSet(object.payloadType) ? globalThis.Number(object.payloadType) : 0,
    };
  },

  toJSON(message: Config): unknown {
    const obj: any = {};
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.padding !== false) {
      obj.padding = message.padding;
    }
    if (message.extension !== false) {
      obj.extension = message.extension;
    }
    if (message.csrcCount !== 0) {
      obj.csrcCount = Math.round(message.csrcCount);
    }
    if (message.marker !== false) {
      obj.marker = message.marker;
    }
    if (message.payloadType !== 0) {
      obj.payloadType = Math.round(message.payloadType);
    }
    return obj;
  },

  create(base?: DeepPartial<Config>): Config {
    return Config.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Config>): Config {
    const message = createBaseConfig();
    message.version = object.version ?? 0;
    message.padding = object.padding ?? false;
    message.extension = object.extension ?? false;
    message.csrcCount = object.csrcCount ?? 0;
    message.marker = object.marker ?? false;
    message.payloadType = object.payloadType ?? 0;
    return message;
  },
};

messageTypeRegistry.set(Config.$type, Config);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
