// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.33.4
// source: transport/internet/finalmask/fragment/config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { messageTypeRegistry } from "../../../../typeRegistry";

export const protobufPackage = "xray.transport.internet.finalmask.fragment";

export interface Config {
  $type: "xray.transport.internet.finalmask.fragment.Config";
  packetsFrom: number;
  packetsTo: number;
  maxSplitMin: number;
  maxSplitMax: number;
  lengthsMin: number[];
  lengthsMax: number[];
  delaysMin: number[];
  delaysMax: number[];
}

function createBaseConfig(): Config {
  return {
    $type: "xray.transport.internet.finalmask.fragment.Config",
    packetsFrom: 0,
    packetsTo: 0,
    maxSplitMin: 0,
    maxSplitMax: 0,
    lengthsMin: [],
    lengthsMax: [],
    delaysMin: [],
    delaysMax: [],
  };
}

export const Config: MessageFns<Config, "xray.transport.internet.finalmask.fragment.Config"> = {
  $type: "xray.transport.internet.finalmask.fragment.Config" as const,

  encode(message: Config, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.packetsFrom !== 0) {
      writer.uint32(8).int64(message.packetsFrom);
    }
    if (message.packetsTo !== 0) {
      writer.uint32(16).int64(message.packetsTo);
    }
    if (message.maxSplitMin !== 0) {
      writer.uint32(56).int64(message.maxSplitMin);
    }
    if (message.maxSplitMax !== 0) {
      writer.uint32(64).int64(message.maxSplitMax);
    }
    writer.uint32(74).fork();
    for (const v of message.lengthsMin) {
      writer.int64(v);
    }
    writer.join();
    writer.uint32(82).fork();
    for (const v of message.lengthsMax) {
      writer.int64(v);
    }
    writer.join();
    writer.uint32(90).fork();
    for (const v of message.delaysMin) {
      writer.int64(v);
    }
    writer.join();
    writer.uint32(98).fork();
    for (const v of message.delaysMax) {
      writer.int64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Config {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.packetsFrom = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.packetsTo = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.maxSplitMin = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.maxSplitMax = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag === 72) {
            message.lengthsMin.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 74) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.lengthsMin.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
        case 10: {
          if (tag === 80) {
            message.lengthsMax.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 82) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.lengthsMax.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
        case 11: {
          if (tag === 88) {
            message.delaysMin.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 90) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.delaysMin.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
        case 12: {
          if (tag === 96) {
            message.delaysMax.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 98) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.delaysMax.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Config {
    return {
      $type: Config.$type,
      packetsFrom: isSet(object.packetsFrom)
        ? globalThis.Number(object.packetsFrom)
        : isSet(object.packets_from)
        ? globalThis.Number(object.packets_from)
        : 0,
      packetsTo: isSet(object.packetsTo)
        ? globalThis.Number(object.packetsTo)
        : isSet(object.packets_to)
        ? globalThis.Number(object.packets_to)
        : 0,
      maxSplitMin: isSet(object.maxSplitMin)
        ? globalThis.Number(object.maxSplitMin)
        : isSet(object.max_split_min)
        ? globalThis.Number(object.max_split_min)
        : 0,
      maxSplitMax: isSet(object.maxSplitMax)
        ? globalThis.Number(object.maxSplitMax)
        : isSet(object.max_split_max)
        ? globalThis.Number(object.max_split_max)
        : 0,
      lengthsMin: globalThis.Array.isArray(object?.lengthsMin)
        ? object.lengthsMin.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.lengths_min)
        ? object.lengths_min.map((e: any) => globalThis.Number(e))
        : [],
      lengthsMax: globalThis.Array.isArray(object?.lengthsMax)
        ? object.lengthsMax.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.lengths_max)
        ? object.lengths_max.map((e: any) => globalThis.Number(e))
        : [],
      delaysMin: globalThis.Array.isArray(object?.delaysMin)
        ? object.delaysMin.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.delays_min)
        ? object.delays_min.map((e: any) => globalThis.Number(e))
        : [],
      delaysMax: globalThis.Array.isArray(object?.delaysMax)
        ? object.delaysMax.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.delays_max)
        ? object.delays_max.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: Config): unknown {
    const obj: any = {};
    if (message.packetsFrom !== 0) {
      obj.packetsFrom = Math.round(message.packetsFrom);
    }
    if (message.packetsTo !== 0) {
      obj.packetsTo = Math.round(message.packetsTo);
    }
    if (message.maxSplitMin !== 0) {
      obj.maxSplitMin = Math.round(message.maxSplitMin);
    }
    if (message.maxSplitMax !== 0) {
      obj.maxSplitMax = Math.round(message.maxSplitMax);
    }
    if (message.lengthsMin?.length) {
      obj.lengthsMin = message.lengthsMin.map((e) => Math.round(e));
    }
    if (message.lengthsMax?.length) {
      obj.lengthsMax = message.lengthsMax.map((e) => Math.round(e));
    }
    if (message.delaysMin?.length) {
      obj.delaysMin = message.delaysMin.map((e) => Math.round(e));
    }
    if (message.delaysMax?.length) {
      obj.delaysMax = message.delaysMax.map((e) => Math.round(e));
    }
    return obj;
  },

  create(base?: DeepPartial<Config>): Config {
    return Config.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Config>): Config {
    const message = createBaseConfig();
    message.packetsFrom = object.packetsFrom ?? 0;
    message.packetsTo = object.packetsTo ?? 0;
    message.maxSplitMin = object.maxSplitMin ?? 0;
    message.maxSplitMax = object.maxSplitMax ?? 0;
    message.lengthsMin = object.lengthsMin?.map((e) => e) || [];
    message.lengthsMax = object.lengthsMax?.map((e) => e) || [];
    message.delaysMin = object.delaysMin?.map((e) => e) || [];
    message.delaysMax = object.delaysMax?.map((e) => e) || [];
    return message;
  },
};

messageTypeRegistry.set(Config.$type, Config);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
