// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.7
//   protoc               v5.29.3
// source: proxy/shadowsocks_2022/config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { IPOrDomain } from "../../common/net/address";
import { Network, networkFromJSON, networkToJSON } from "../../common/net/network";
import { User } from "../../common/protocol/user";
import { messageTypeRegistry } from "../../typeRegistry";

export const protobufPackage = "xray.proxy.shadowsocks_2022";

export interface ServerConfig {
  $type: "xray.proxy.shadowsocks_2022.ServerConfig";
  method: string;
  key: string;
  email: string;
  level: number;
  network: Network[];
}

export interface MultiUserServerConfig {
  $type: "xray.proxy.shadowsocks_2022.MultiUserServerConfig";
  method: string;
  key: string;
  users: User[];
  network: Network[];
}

export interface RelayDestination {
  $type: "xray.proxy.shadowsocks_2022.RelayDestination";
  key: string;
  address: IPOrDomain | undefined;
  port: number;
  email: string;
  level: number;
}

export interface RelayServerConfig {
  $type: "xray.proxy.shadowsocks_2022.RelayServerConfig";
  method: string;
  key: string;
  destinations: RelayDestination[];
  network: Network[];
}

export interface Account {
  $type: "xray.proxy.shadowsocks_2022.Account";
  key: string;
}

export interface ClientConfig {
  $type: "xray.proxy.shadowsocks_2022.ClientConfig";
  address: IPOrDomain | undefined;
  port: number;
  method: string;
  key: string;
  udpOverTcp: boolean;
  udpOverTcpVersion: number;
}

function createBaseServerConfig(): ServerConfig {
  return { $type: "xray.proxy.shadowsocks_2022.ServerConfig", method: "", key: "", email: "", level: 0, network: [] };
}

export const ServerConfig: MessageFns<ServerConfig, "xray.proxy.shadowsocks_2022.ServerConfig"> = {
  $type: "xray.proxy.shadowsocks_2022.ServerConfig" as const,

  encode(message: ServerConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.method !== "") {
      writer.uint32(10).string(message.method);
    }
    if (message.key !== "") {
      writer.uint32(18).string(message.key);
    }
    if (message.email !== "") {
      writer.uint32(26).string(message.email);
    }
    if (message.level !== 0) {
      writer.uint32(32).int32(message.level);
    }
    writer.uint32(42).fork();
    for (const v of message.network) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.method = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.level = reader.int32();
          continue;
        }
        case 5: {
          if (tag === 40) {
            message.network.push(reader.int32() as any);

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.network.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerConfig {
    return {
      $type: ServerConfig.$type,
      method: isSet(object.method) ? globalThis.String(object.method) : "",
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      level: isSet(object.level) ? globalThis.Number(object.level) : 0,
      network: globalThis.Array.isArray(object?.network) ? object.network.map((e: any) => networkFromJSON(e)) : [],
    };
  },

  toJSON(message: ServerConfig): unknown {
    const obj: any = {};
    if (message.method !== "") {
      obj.method = message.method;
    }
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.level !== 0) {
      obj.level = Math.round(message.level);
    }
    if (message.network?.length) {
      obj.network = message.network.map((e) => networkToJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ServerConfig>): ServerConfig {
    return ServerConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ServerConfig>): ServerConfig {
    const message = createBaseServerConfig();
    message.method = object.method ?? "";
    message.key = object.key ?? "";
    message.email = object.email ?? "";
    message.level = object.level ?? 0;
    message.network = object.network?.map((e) => e) || [];
    return message;
  },
};

messageTypeRegistry.set(ServerConfig.$type, ServerConfig);

function createBaseMultiUserServerConfig(): MultiUserServerConfig {
  return { $type: "xray.proxy.shadowsocks_2022.MultiUserServerConfig", method: "", key: "", users: [], network: [] };
}

export const MultiUserServerConfig: MessageFns<
  MultiUserServerConfig,
  "xray.proxy.shadowsocks_2022.MultiUserServerConfig"
> = {
  $type: "xray.proxy.shadowsocks_2022.MultiUserServerConfig" as const,

  encode(message: MultiUserServerConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.method !== "") {
      writer.uint32(10).string(message.method);
    }
    if (message.key !== "") {
      writer.uint32(18).string(message.key);
    }
    for (const v of message.users) {
      User.encode(v!, writer.uint32(26).fork()).join();
    }
    writer.uint32(34).fork();
    for (const v of message.network) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MultiUserServerConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMultiUserServerConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.method = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.users.push(User.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag === 32) {
            message.network.push(reader.int32() as any);

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.network.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MultiUserServerConfig {
    return {
      $type: MultiUserServerConfig.$type,
      method: isSet(object.method) ? globalThis.String(object.method) : "",
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      users: globalThis.Array.isArray(object?.users) ? object.users.map((e: any) => User.fromJSON(e)) : [],
      network: globalThis.Array.isArray(object?.network) ? object.network.map((e: any) => networkFromJSON(e)) : [],
    };
  },

  toJSON(message: MultiUserServerConfig): unknown {
    const obj: any = {};
    if (message.method !== "") {
      obj.method = message.method;
    }
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.users?.length) {
      obj.users = message.users.map((e) => User.toJSON(e));
    }
    if (message.network?.length) {
      obj.network = message.network.map((e) => networkToJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<MultiUserServerConfig>): MultiUserServerConfig {
    return MultiUserServerConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MultiUserServerConfig>): MultiUserServerConfig {
    const message = createBaseMultiUserServerConfig();
    message.method = object.method ?? "";
    message.key = object.key ?? "";
    message.users = object.users?.map((e) => User.fromPartial(e)) || [];
    message.network = object.network?.map((e) => e) || [];
    return message;
  },
};

messageTypeRegistry.set(MultiUserServerConfig.$type, MultiUserServerConfig);

function createBaseRelayDestination(): RelayDestination {
  return {
    $type: "xray.proxy.shadowsocks_2022.RelayDestination",
    key: "",
    address: undefined,
    port: 0,
    email: "",
    level: 0,
  };
}

export const RelayDestination: MessageFns<RelayDestination, "xray.proxy.shadowsocks_2022.RelayDestination"> = {
  $type: "xray.proxy.shadowsocks_2022.RelayDestination" as const,

  encode(message: RelayDestination, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.address !== undefined) {
      IPOrDomain.encode(message.address, writer.uint32(18).fork()).join();
    }
    if (message.port !== 0) {
      writer.uint32(24).uint32(message.port);
    }
    if (message.email !== "") {
      writer.uint32(34).string(message.email);
    }
    if (message.level !== 0) {
      writer.uint32(40).int32(message.level);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RelayDestination {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRelayDestination();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.address = IPOrDomain.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.port = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.level = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RelayDestination {
    return {
      $type: RelayDestination.$type,
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      address: isSet(object.address) ? IPOrDomain.fromJSON(object.address) : undefined,
      port: isSet(object.port) ? globalThis.Number(object.port) : 0,
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      level: isSet(object.level) ? globalThis.Number(object.level) : 0,
    };
  },

  toJSON(message: RelayDestination): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.address !== undefined) {
      obj.address = IPOrDomain.toJSON(message.address);
    }
    if (message.port !== 0) {
      obj.port = Math.round(message.port);
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.level !== 0) {
      obj.level = Math.round(message.level);
    }
    return obj;
  },

  create(base?: DeepPartial<RelayDestination>): RelayDestination {
    return RelayDestination.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RelayDestination>): RelayDestination {
    const message = createBaseRelayDestination();
    message.key = object.key ?? "";
    message.address = (object.address !== undefined && object.address !== null)
      ? IPOrDomain.fromPartial(object.address)
      : undefined;
    message.port = object.port ?? 0;
    message.email = object.email ?? "";
    message.level = object.level ?? 0;
    return message;
  },
};

messageTypeRegistry.set(RelayDestination.$type, RelayDestination);

function createBaseRelayServerConfig(): RelayServerConfig {
  return { $type: "xray.proxy.shadowsocks_2022.RelayServerConfig", method: "", key: "", destinations: [], network: [] };
}

export const RelayServerConfig: MessageFns<RelayServerConfig, "xray.proxy.shadowsocks_2022.RelayServerConfig"> = {
  $type: "xray.proxy.shadowsocks_2022.RelayServerConfig" as const,

  encode(message: RelayServerConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.method !== "") {
      writer.uint32(10).string(message.method);
    }
    if (message.key !== "") {
      writer.uint32(18).string(message.key);
    }
    for (const v of message.destinations) {
      RelayDestination.encode(v!, writer.uint32(26).fork()).join();
    }
    writer.uint32(34).fork();
    for (const v of message.network) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RelayServerConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRelayServerConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.method = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.destinations.push(RelayDestination.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag === 32) {
            message.network.push(reader.int32() as any);

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.network.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RelayServerConfig {
    return {
      $type: RelayServerConfig.$type,
      method: isSet(object.method) ? globalThis.String(object.method) : "",
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      destinations: globalThis.Array.isArray(object?.destinations)
        ? object.destinations.map((e: any) => RelayDestination.fromJSON(e))
        : [],
      network: globalThis.Array.isArray(object?.network) ? object.network.map((e: any) => networkFromJSON(e)) : [],
    };
  },

  toJSON(message: RelayServerConfig): unknown {
    const obj: any = {};
    if (message.method !== "") {
      obj.method = message.method;
    }
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.destinations?.length) {
      obj.destinations = message.destinations.map((e) => RelayDestination.toJSON(e));
    }
    if (message.network?.length) {
      obj.network = message.network.map((e) => networkToJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<RelayServerConfig>): RelayServerConfig {
    return RelayServerConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RelayServerConfig>): RelayServerConfig {
    const message = createBaseRelayServerConfig();
    message.method = object.method ?? "";
    message.key = object.key ?? "";
    message.destinations = object.destinations?.map((e) => RelayDestination.fromPartial(e)) || [];
    message.network = object.network?.map((e) => e) || [];
    return message;
  },
};

messageTypeRegistry.set(RelayServerConfig.$type, RelayServerConfig);

function createBaseAccount(): Account {
  return { $type: "xray.proxy.shadowsocks_2022.Account", key: "" };
}

export const Account: MessageFns<Account, "xray.proxy.shadowsocks_2022.Account"> = {
  $type: "xray.proxy.shadowsocks_2022.Account" as const,

  encode(message: Account, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Account {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Account {
    return { $type: Account.$type, key: isSet(object.key) ? globalThis.String(object.key) : "" };
  },

  toJSON(message: Account): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    return obj;
  },

  create(base?: DeepPartial<Account>): Account {
    return Account.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Account>): Account {
    const message = createBaseAccount();
    message.key = object.key ?? "";
    return message;
  },
};

messageTypeRegistry.set(Account.$type, Account);

function createBaseClientConfig(): ClientConfig {
  return {
    $type: "xray.proxy.shadowsocks_2022.ClientConfig",
    address: undefined,
    port: 0,
    method: "",
    key: "",
    udpOverTcp: false,
    udpOverTcpVersion: 0,
  };
}

export const ClientConfig: MessageFns<ClientConfig, "xray.proxy.shadowsocks_2022.ClientConfig"> = {
  $type: "xray.proxy.shadowsocks_2022.ClientConfig" as const,

  encode(message: ClientConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== undefined) {
      IPOrDomain.encode(message.address, writer.uint32(10).fork()).join();
    }
    if (message.port !== 0) {
      writer.uint32(16).uint32(message.port);
    }
    if (message.method !== "") {
      writer.uint32(26).string(message.method);
    }
    if (message.key !== "") {
      writer.uint32(34).string(message.key);
    }
    if (message.udpOverTcp !== false) {
      writer.uint32(40).bool(message.udpOverTcp);
    }
    if (message.udpOverTcpVersion !== 0) {
      writer.uint32(48).uint32(message.udpOverTcpVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClientConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClientConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = IPOrDomain.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.port = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.method = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.udpOverTcp = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.udpOverTcpVersion = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClientConfig {
    return {
      $type: ClientConfig.$type,
      address: isSet(object.address) ? IPOrDomain.fromJSON(object.address) : undefined,
      port: isSet(object.port) ? globalThis.Number(object.port) : 0,
      method: isSet(object.method) ? globalThis.String(object.method) : "",
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      udpOverTcp: isSet(object.udpOverTcp) ? globalThis.Boolean(object.udpOverTcp) : false,
      udpOverTcpVersion: isSet(object.udpOverTcpVersion) ? globalThis.Number(object.udpOverTcpVersion) : 0,
    };
  },

  toJSON(message: ClientConfig): unknown {
    const obj: any = {};
    if (message.address !== undefined) {
      obj.address = IPOrDomain.toJSON(message.address);
    }
    if (message.port !== 0) {
      obj.port = Math.round(message.port);
    }
    if (message.method !== "") {
      obj.method = message.method;
    }
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.udpOverTcp !== false) {
      obj.udpOverTcp = message.udpOverTcp;
    }
    if (message.udpOverTcpVersion !== 0) {
      obj.udpOverTcpVersion = Math.round(message.udpOverTcpVersion);
    }
    return obj;
  },

  create(base?: DeepPartial<ClientConfig>): ClientConfig {
    return ClientConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ClientConfig>): ClientConfig {
    const message = createBaseClientConfig();
    message.address = (object.address !== undefined && object.address !== null)
      ? IPOrDomain.fromPartial(object.address)
      : undefined;
    message.port = object.port ?? 0;
    message.method = object.method ?? "";
    message.key = object.key ?? "";
    message.udpOverTcp = object.udpOverTcp ?? false;
    message.udpOverTcpVersion = object.udpOverTcpVersion ?? 0;
    return message;
  },
};

messageTypeRegistry.set(ClientConfig.$type, ClientConfig);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
