// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.33.4
// source: proxy/dokodemo/config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { IPOrDomain } from "../../common/net/address";
import { Network, networkFromJSON, networkToJSON } from "../../common/net/network";
import { messageTypeRegistry } from "../../typeRegistry";

export const protobufPackage = "xray.proxy.dokodemo";

export interface Config {
  $type: "xray.proxy.dokodemo.Config";
  /** List of networks that the Dokodemo accepts. */
  allowedNetworks: Network[];
  rewriteAddress: IPOrDomain | undefined;
  rewritePort: number;
  portMap: { [key: string]: string };
  followRedirect: boolean;
  userLevel: number;
}

export interface Config_PortMapEntry {
  $type: "xray.proxy.dokodemo.Config.PortMapEntry";
  key: string;
  value: string;
}

function createBaseConfig(): Config {
  return {
    $type: "xray.proxy.dokodemo.Config",
    allowedNetworks: [],
    rewriteAddress: undefined,
    rewritePort: 0,
    portMap: {},
    followRedirect: false,
    userLevel: 0,
  };
}

export const Config: MessageFns<Config, "xray.proxy.dokodemo.Config"> = {
  $type: "xray.proxy.dokodemo.Config" as const,

  encode(message: Config, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(58).fork();
    for (const v of message.allowedNetworks) {
      writer.int32(v);
    }
    writer.join();
    if (message.rewriteAddress !== undefined) {
      IPOrDomain.encode(message.rewriteAddress, writer.uint32(10).fork()).join();
    }
    if (message.rewritePort !== 0) {
      writer.uint32(16).uint32(message.rewritePort);
    }
    globalThis.Object.entries(message.portMap).forEach(([key, value]: [string, string]) => {
      Config_PortMapEntry.encode(
        { $type: "xray.proxy.dokodemo.Config.PortMapEntry", key: key as any, value },
        writer.uint32(26).fork(),
      ).join();
    });
    if (message.followRedirect !== false) {
      writer.uint32(40).bool(message.followRedirect);
    }
    if (message.userLevel !== 0) {
      writer.uint32(48).uint32(message.userLevel);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Config {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 7: {
          if (tag === 56) {
            message.allowedNetworks.push(reader.int32() as any);

            continue;
          }

          if (tag === 58) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.allowedNetworks.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.rewriteAddress = IPOrDomain.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.rewritePort = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = Config_PortMapEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.portMap[entry3.key] = entry3.value;
          }
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.followRedirect = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.userLevel = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Config {
    return {
      $type: Config.$type,
      allowedNetworks: globalThis.Array.isArray(object?.allowedNetworks)
        ? object.allowedNetworks.map((e: any) => networkFromJSON(e))
        : globalThis.Array.isArray(object?.allowed_networks)
        ? object.allowed_networks.map((e: any) => networkFromJSON(e))
        : [],
      rewriteAddress: isSet(object.rewriteAddress)
        ? IPOrDomain.fromJSON(object.rewriteAddress)
        : isSet(object.rewrite_address)
        ? IPOrDomain.fromJSON(object.rewrite_address)
        : undefined,
      rewritePort: isSet(object.rewritePort)
        ? globalThis.Number(object.rewritePort)
        : isSet(object.rewrite_port)
        ? globalThis.Number(object.rewrite_port)
        : 0,
      portMap: isObject(object.portMap)
        ? (globalThis.Object.entries(object.portMap) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : isObject(object.port_map)
        ? (globalThis.Object.entries(object.port_map) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      followRedirect: isSet(object.followRedirect)
        ? globalThis.Boolean(object.followRedirect)
        : isSet(object.follow_redirect)
        ? globalThis.Boolean(object.follow_redirect)
        : false,
      userLevel: isSet(object.userLevel)
        ? globalThis.Number(object.userLevel)
        : isSet(object.user_level)
        ? globalThis.Number(object.user_level)
        : 0,
    };
  },

  toJSON(message: Config): unknown {
    const obj: any = {};
    if (message.allowedNetworks?.length) {
      obj.allowedNetworks = message.allowedNetworks.map((e) => networkToJSON(e));
    }
    if (message.rewriteAddress !== undefined) {
      obj.rewriteAddress = IPOrDomain.toJSON(message.rewriteAddress);
    }
    if (message.rewritePort !== 0) {
      obj.rewritePort = Math.round(message.rewritePort);
    }
    if (message.portMap) {
      const entries = globalThis.Object.entries(message.portMap) as [string, string][];
      if (entries.length > 0) {
        obj.portMap = {};
        entries.forEach(([k, v]) => {
          obj.portMap[k] = v;
        });
      }
    }
    if (message.followRedirect !== false) {
      obj.followRedirect = message.followRedirect;
    }
    if (message.userLevel !== 0) {
      obj.userLevel = Math.round(message.userLevel);
    }
    return obj;
  },

  create(base?: DeepPartial<Config>): Config {
    return Config.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Config>): Config {
    const message = createBaseConfig();
    message.allowedNetworks = object.allowedNetworks?.map((e) => e) || [];
    message.rewriteAddress = (object.rewriteAddress !== undefined && object.rewriteAddress !== null)
      ? IPOrDomain.fromPartial(object.rewriteAddress)
      : undefined;
    message.rewritePort = object.rewritePort ?? 0;
    message.portMap = (globalThis.Object.entries(object.portMap ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.followRedirect = object.followRedirect ?? false;
    message.userLevel = object.userLevel ?? 0;
    return message;
  },
};

messageTypeRegistry.set(Config.$type, Config);

function createBaseConfig_PortMapEntry(): Config_PortMapEntry {
  return { $type: "xray.proxy.dokodemo.Config.PortMapEntry", key: "", value: "" };
}

export const Config_PortMapEntry: MessageFns<Config_PortMapEntry, "xray.proxy.dokodemo.Config.PortMapEntry"> = {
  $type: "xray.proxy.dokodemo.Config.PortMapEntry" as const,

  encode(message: Config_PortMapEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Config_PortMapEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfig_PortMapEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Config_PortMapEntry {
    return {
      $type: Config_PortMapEntry.$type,
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: Config_PortMapEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create(base?: DeepPartial<Config_PortMapEntry>): Config_PortMapEntry {
    return Config_PortMapEntry.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Config_PortMapEntry>): Config_PortMapEntry {
    const message = createBaseConfig_PortMapEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

messageTypeRegistry.set(Config_PortMapEntry.$type, Config_PortMapEntry);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
