// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.33.4
// source: transport/internet/finalmask/salamander/config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { messageTypeRegistry } from "../../../../typeRegistry";

export const protobufPackage = "xray.transport.internet.finalmask.salamander";

export interface Config {
  $type: "xray.transport.internet.finalmask.salamander.Config";
  password: string;
}

export interface GeckoConfig {
  $type: "xray.transport.internet.finalmask.salamander.GeckoConfig";
  password: string;
  MinPacketSize: number;
  MaxPacketSize: number;
}

function createBaseConfig(): Config {
  return { $type: "xray.transport.internet.finalmask.salamander.Config", password: "" };
}

export const Config: MessageFns<Config, "xray.transport.internet.finalmask.salamander.Config"> = {
  $type: "xray.transport.internet.finalmask.salamander.Config" as const,

  encode(message: Config, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.password !== "") {
      writer.uint32(10).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Config {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Config {
    return { $type: Config.$type, password: isSet(object.password) ? globalThis.String(object.password) : "" };
  },

  toJSON(message: Config): unknown {
    const obj: any = {};
    if (message.password !== "") {
      obj.password = message.password;
    }
    return obj;
  },

  create(base?: DeepPartial<Config>): Config {
    return Config.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Config>): Config {
    const message = createBaseConfig();
    message.password = object.password ?? "";
    return message;
  },
};

messageTypeRegistry.set(Config.$type, Config);

function createBaseGeckoConfig(): GeckoConfig {
  return {
    $type: "xray.transport.internet.finalmask.salamander.GeckoConfig",
    password: "",
    MinPacketSize: 0,
    MaxPacketSize: 0,
  };
}

export const GeckoConfig: MessageFns<GeckoConfig, "xray.transport.internet.finalmask.salamander.GeckoConfig"> = {
  $type: "xray.transport.internet.finalmask.salamander.GeckoConfig" as const,

  encode(message: GeckoConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.password !== "") {
      writer.uint32(10).string(message.password);
    }
    if (message.MinPacketSize !== 0) {
      writer.uint32(16).int32(message.MinPacketSize);
    }
    if (message.MaxPacketSize !== 0) {
      writer.uint32(24).int32(message.MaxPacketSize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GeckoConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGeckoConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.MinPacketSize = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.MaxPacketSize = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GeckoConfig {
    return {
      $type: GeckoConfig.$type,
      password: isSet(object.password) ? globalThis.String(object.password) : "",
      MinPacketSize: isSet(object.MinPacketSize) ? globalThis.Number(object.MinPacketSize) : 0,
      MaxPacketSize: isSet(object.MaxPacketSize) ? globalThis.Number(object.MaxPacketSize) : 0,
    };
  },

  toJSON(message: GeckoConfig): unknown {
    const obj: any = {};
    if (message.password !== "") {
      obj.password = message.password;
    }
    if (message.MinPacketSize !== 0) {
      obj.MinPacketSize = Math.round(message.MinPacketSize);
    }
    if (message.MaxPacketSize !== 0) {
      obj.MaxPacketSize = Math.round(message.MaxPacketSize);
    }
    return obj;
  },

  create(base?: DeepPartial<GeckoConfig>): GeckoConfig {
    return GeckoConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GeckoConfig>): GeckoConfig {
    const message = createBaseGeckoConfig();
    message.password = object.password ?? "";
    message.MinPacketSize = object.MinPacketSize ?? 0;
    message.MaxPacketSize = object.MaxPacketSize ?? 0;
    return message;
  },
};

messageTypeRegistry.set(GeckoConfig.$type, GeckoConfig);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
