// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.7
//   protoc               v5.28.3
// source: transport/internet/headers/http/config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { messageTypeRegistry } from "../../../../typeRegistry";

export const protobufPackage = "xray.transport.internet.headers.http";

export interface Header {
  $type: "xray.transport.internet.headers.http.Header";
  /** "Accept", "Cookie", etc */
  name: string;
  /**
   * Each entry must be valid in one piece. Random entry will be chosen if
   * multiple entries present.
   */
  value: string[];
}

/** HTTP version. Default value "1.1". */
export interface Version {
  $type: "xray.transport.internet.headers.http.Version";
  value: string;
}

/** HTTP method. Default value "GET". */
export interface Method {
  $type: "xray.transport.internet.headers.http.Method";
  value: string;
}

export interface RequestConfig {
  $type: "xray.transport.internet.headers.http.RequestConfig";
  /** Full HTTP version like "1.1". */
  version:
    | Version
    | undefined;
  /** GET, POST, CONNECT etc */
  method:
    | Method
    | undefined;
  /** URI like "/login.php" */
  uri: string[];
  header: Header[];
}

export interface Status {
  $type: "xray.transport.internet.headers.http.Status";
  /** Status code. Default "200". */
  code: string;
  /** Statue reason. Default "OK". */
  reason: string;
}

export interface ResponseConfig {
  $type: "xray.transport.internet.headers.http.ResponseConfig";
  version: Version | undefined;
  status: Status | undefined;
  header: Header[];
}

export interface Config {
  $type: "xray.transport.internet.headers.http.Config";
  /**
   * Settings for authenticating requests. If not set, client side will not send
   * authenication header, and server side will bypass authentication.
   */
  request:
    | RequestConfig
    | undefined;
  /**
   * Settings for authenticating responses. If not set, client side will bypass
   * authentication, and server side will not send authentication header.
   */
  response: ResponseConfig | undefined;
}

function createBaseHeader(): Header {
  return { $type: "xray.transport.internet.headers.http.Header", name: "", value: [] };
}

export const Header: MessageFns<Header, "xray.transport.internet.headers.http.Header"> = {
  $type: "xray.transport.internet.headers.http.Header" as const,

  encode(message: Header, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    for (const v of message.value) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Header {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeader();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Header {
    return {
      $type: Header.$type,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      value: globalThis.Array.isArray(object?.value) ? object.value.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: Header): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.value?.length) {
      obj.value = message.value;
    }
    return obj;
  },

  create(base?: DeepPartial<Header>): Header {
    return Header.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Header>): Header {
    const message = createBaseHeader();
    message.name = object.name ?? "";
    message.value = object.value?.map((e) => e) || [];
    return message;
  },
};

messageTypeRegistry.set(Header.$type, Header);

function createBaseVersion(): Version {
  return { $type: "xray.transport.internet.headers.http.Version", value: "" };
}

export const Version: MessageFns<Version, "xray.transport.internet.headers.http.Version"> = {
  $type: "xray.transport.internet.headers.http.Version" as const,

  encode(message: Version, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== "") {
      writer.uint32(10).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Version {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVersion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Version {
    return { $type: Version.$type, value: isSet(object.value) ? globalThis.String(object.value) : "" };
  },

  toJSON(message: Version): unknown {
    const obj: any = {};
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create(base?: DeepPartial<Version>): Version {
    return Version.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Version>): Version {
    const message = createBaseVersion();
    message.value = object.value ?? "";
    return message;
  },
};

messageTypeRegistry.set(Version.$type, Version);

function createBaseMethod(): Method {
  return { $type: "xray.transport.internet.headers.http.Method", value: "" };
}

export const Method: MessageFns<Method, "xray.transport.internet.headers.http.Method"> = {
  $type: "xray.transport.internet.headers.http.Method" as const,

  encode(message: Method, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== "") {
      writer.uint32(10).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Method {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMethod();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Method {
    return { $type: Method.$type, value: isSet(object.value) ? globalThis.String(object.value) : "" };
  },

  toJSON(message: Method): unknown {
    const obj: any = {};
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create(base?: DeepPartial<Method>): Method {
    return Method.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Method>): Method {
    const message = createBaseMethod();
    message.value = object.value ?? "";
    return message;
  },
};

messageTypeRegistry.set(Method.$type, Method);

function createBaseRequestConfig(): RequestConfig {
  return {
    $type: "xray.transport.internet.headers.http.RequestConfig",
    version: undefined,
    method: undefined,
    uri: [],
    header: [],
  };
}

export const RequestConfig: MessageFns<RequestConfig, "xray.transport.internet.headers.http.RequestConfig"> = {
  $type: "xray.transport.internet.headers.http.RequestConfig" as const,

  encode(message: RequestConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version !== undefined) {
      Version.encode(message.version, writer.uint32(10).fork()).join();
    }
    if (message.method !== undefined) {
      Method.encode(message.method, writer.uint32(18).fork()).join();
    }
    for (const v of message.uri) {
      writer.uint32(26).string(v!);
    }
    for (const v of message.header) {
      Header.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.version = Version.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.method = Method.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.uri.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.header.push(Header.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestConfig {
    return {
      $type: RequestConfig.$type,
      version: isSet(object.version) ? Version.fromJSON(object.version) : undefined,
      method: isSet(object.method) ? Method.fromJSON(object.method) : undefined,
      uri: globalThis.Array.isArray(object?.uri) ? object.uri.map((e: any) => globalThis.String(e)) : [],
      header: globalThis.Array.isArray(object?.header) ? object.header.map((e: any) => Header.fromJSON(e)) : [],
    };
  },

  toJSON(message: RequestConfig): unknown {
    const obj: any = {};
    if (message.version !== undefined) {
      obj.version = Version.toJSON(message.version);
    }
    if (message.method !== undefined) {
      obj.method = Method.toJSON(message.method);
    }
    if (message.uri?.length) {
      obj.uri = message.uri;
    }
    if (message.header?.length) {
      obj.header = message.header.map((e) => Header.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<RequestConfig>): RequestConfig {
    return RequestConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RequestConfig>): RequestConfig {
    const message = createBaseRequestConfig();
    message.version = (object.version !== undefined && object.version !== null)
      ? Version.fromPartial(object.version)
      : undefined;
    message.method = (object.method !== undefined && object.method !== null)
      ? Method.fromPartial(object.method)
      : undefined;
    message.uri = object.uri?.map((e) => e) || [];
    message.header = object.header?.map((e) => Header.fromPartial(e)) || [];
    return message;
  },
};

messageTypeRegistry.set(RequestConfig.$type, RequestConfig);

function createBaseStatus(): Status {
  return { $type: "xray.transport.internet.headers.http.Status", code: "", reason: "" };
}

export const Status: MessageFns<Status, "xray.transport.internet.headers.http.Status"> = {
  $type: "xray.transport.internet.headers.http.Status" as const,

  encode(message: Status, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.reason !== "") {
      writer.uint32(18).string(message.reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Status {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Status {
    return {
      $type: Status.$type,
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
    };
  },

  toJSON(message: Status): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    return obj;
  },

  create(base?: DeepPartial<Status>): Status {
    return Status.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Status>): Status {
    const message = createBaseStatus();
    message.code = object.code ?? "";
    message.reason = object.reason ?? "";
    return message;
  },
};

messageTypeRegistry.set(Status.$type, Status);

function createBaseResponseConfig(): ResponseConfig {
  return {
    $type: "xray.transport.internet.headers.http.ResponseConfig",
    version: undefined,
    status: undefined,
    header: [],
  };
}

export const ResponseConfig: MessageFns<ResponseConfig, "xray.transport.internet.headers.http.ResponseConfig"> = {
  $type: "xray.transport.internet.headers.http.ResponseConfig" as const,

  encode(message: ResponseConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version !== undefined) {
      Version.encode(message.version, writer.uint32(10).fork()).join();
    }
    if (message.status !== undefined) {
      Status.encode(message.status, writer.uint32(18).fork()).join();
    }
    for (const v of message.header) {
      Header.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResponseConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponseConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.version = Version.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = Status.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.header.push(Header.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResponseConfig {
    return {
      $type: ResponseConfig.$type,
      version: isSet(object.version) ? Version.fromJSON(object.version) : undefined,
      status: isSet(object.status) ? Status.fromJSON(object.status) : undefined,
      header: globalThis.Array.isArray(object?.header) ? object.header.map((e: any) => Header.fromJSON(e)) : [],
    };
  },

  toJSON(message: ResponseConfig): unknown {
    const obj: any = {};
    if (message.version !== undefined) {
      obj.version = Version.toJSON(message.version);
    }
    if (message.status !== undefined) {
      obj.status = Status.toJSON(message.status);
    }
    if (message.header?.length) {
      obj.header = message.header.map((e) => Header.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ResponseConfig>): ResponseConfig {
    return ResponseConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ResponseConfig>): ResponseConfig {
    const message = createBaseResponseConfig();
    message.version = (object.version !== undefined && object.version !== null)
      ? Version.fromPartial(object.version)
      : undefined;
    message.status = (object.status !== undefined && object.status !== null)
      ? Status.fromPartial(object.status)
      : undefined;
    message.header = object.header?.map((e) => Header.fromPartial(e)) || [];
    return message;
  },
};

messageTypeRegistry.set(ResponseConfig.$type, ResponseConfig);

function createBaseConfig(): Config {
  return { $type: "xray.transport.internet.headers.http.Config", request: undefined, response: undefined };
}

export const Config: MessageFns<Config, "xray.transport.internet.headers.http.Config"> = {
  $type: "xray.transport.internet.headers.http.Config" as const,

  encode(message: Config, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.request !== undefined) {
      RequestConfig.encode(message.request, writer.uint32(10).fork()).join();
    }
    if (message.response !== undefined) {
      ResponseConfig.encode(message.response, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Config {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.request = RequestConfig.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.response = ResponseConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Config {
    return {
      $type: Config.$type,
      request: isSet(object.request) ? RequestConfig.fromJSON(object.request) : undefined,
      response: isSet(object.response) ? ResponseConfig.fromJSON(object.response) : undefined,
    };
  },

  toJSON(message: Config): unknown {
    const obj: any = {};
    if (message.request !== undefined) {
      obj.request = RequestConfig.toJSON(message.request);
    }
    if (message.response !== undefined) {
      obj.response = ResponseConfig.toJSON(message.response);
    }
    return obj;
  },

  create(base?: DeepPartial<Config>): Config {
    return Config.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Config>): Config {
    const message = createBaseConfig();
    message.request = (object.request !== undefined && object.request !== null)
      ? RequestConfig.fromPartial(object.request)
      : undefined;
    message.response = (object.response !== undefined && object.response !== null)
      ? ResponseConfig.fromPartial(object.response)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(Config.$type, Config);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
