// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: transport/internet/finalmask/noise/config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { messageTypeRegistry } from "../../../../typeRegistry";

export const protobufPackage = "xray.transport.internet.finalmask.noise";

export interface Item {
  $type: "xray.transport.internet.finalmask.noise.Item";
  randMin: number;
  randMax: number;
  randRangeMin: number;
  randRangeMax: number;
  packet: Uint8Array;
  delayMin: number;
  delayMax: number;
}

export interface Config {
  $type: "xray.transport.internet.finalmask.noise.Config";
  resetMin: number;
  resetMax: number;
  items: Item[];
}

function createBaseItem(): Item {
  return {
    $type: "xray.transport.internet.finalmask.noise.Item",
    randMin: 0,
    randMax: 0,
    randRangeMin: 0,
    randRangeMax: 0,
    packet: new Uint8Array(0),
    delayMin: 0,
    delayMax: 0,
  };
}

export const Item: MessageFns<Item, "xray.transport.internet.finalmask.noise.Item"> = {
  $type: "xray.transport.internet.finalmask.noise.Item" as const,

  encode(message: Item, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.randMin !== 0) {
      writer.uint32(8).int64(message.randMin);
    }
    if (message.randMax !== 0) {
      writer.uint32(16).int64(message.randMax);
    }
    if (message.randRangeMin !== 0) {
      writer.uint32(24).int32(message.randRangeMin);
    }
    if (message.randRangeMax !== 0) {
      writer.uint32(32).int32(message.randRangeMax);
    }
    if (message.packet.length !== 0) {
      writer.uint32(42).bytes(message.packet);
    }
    if (message.delayMin !== 0) {
      writer.uint32(48).int64(message.delayMin);
    }
    if (message.delayMax !== 0) {
      writer.uint32(56).int64(message.delayMax);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.randMin = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.randMax = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.randRangeMin = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.randRangeMax = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.packet = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.delayMin = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.delayMax = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Item {
    return {
      $type: Item.$type,
      randMin: isSet(object.randMin)
        ? globalThis.Number(object.randMin)
        : isSet(object.rand_min)
        ? globalThis.Number(object.rand_min)
        : 0,
      randMax: isSet(object.randMax)
        ? globalThis.Number(object.randMax)
        : isSet(object.rand_max)
        ? globalThis.Number(object.rand_max)
        : 0,
      randRangeMin: isSet(object.randRangeMin)
        ? globalThis.Number(object.randRangeMin)
        : isSet(object.rand_range_min)
        ? globalThis.Number(object.rand_range_min)
        : 0,
      randRangeMax: isSet(object.randRangeMax)
        ? globalThis.Number(object.randRangeMax)
        : isSet(object.rand_range_max)
        ? globalThis.Number(object.rand_range_max)
        : 0,
      packet: isSet(object.packet) ? bytesFromBase64(object.packet) : new Uint8Array(0),
      delayMin: isSet(object.delayMin)
        ? globalThis.Number(object.delayMin)
        : isSet(object.delay_min)
        ? globalThis.Number(object.delay_min)
        : 0,
      delayMax: isSet(object.delayMax)
        ? globalThis.Number(object.delayMax)
        : isSet(object.delay_max)
        ? globalThis.Number(object.delay_max)
        : 0,
    };
  },

  toJSON(message: Item): unknown {
    const obj: any = {};
    if (message.randMin !== 0) {
      obj.randMin = Math.round(message.randMin);
    }
    if (message.randMax !== 0) {
      obj.randMax = Math.round(message.randMax);
    }
    if (message.randRangeMin !== 0) {
      obj.randRangeMin = Math.round(message.randRangeMin);
    }
    if (message.randRangeMax !== 0) {
      obj.randRangeMax = Math.round(message.randRangeMax);
    }
    if (message.packet.length !== 0) {
      obj.packet = base64FromBytes(message.packet);
    }
    if (message.delayMin !== 0) {
      obj.delayMin = Math.round(message.delayMin);
    }
    if (message.delayMax !== 0) {
      obj.delayMax = Math.round(message.delayMax);
    }
    return obj;
  },

  create(base?: DeepPartial<Item>): Item {
    return Item.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Item>): Item {
    const message = createBaseItem();
    message.randMin = object.randMin ?? 0;
    message.randMax = object.randMax ?? 0;
    message.randRangeMin = object.randRangeMin ?? 0;
    message.randRangeMax = object.randRangeMax ?? 0;
    message.packet = object.packet ?? new Uint8Array(0);
    message.delayMin = object.delayMin ?? 0;
    message.delayMax = object.delayMax ?? 0;
    return message;
  },
};

messageTypeRegistry.set(Item.$type, Item);

function createBaseConfig(): Config {
  return { $type: "xray.transport.internet.finalmask.noise.Config", resetMin: 0, resetMax: 0, items: [] };
}

export const Config: MessageFns<Config, "xray.transport.internet.finalmask.noise.Config"> = {
  $type: "xray.transport.internet.finalmask.noise.Config" as const,

  encode(message: Config, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.resetMin !== 0) {
      writer.uint32(8).int64(message.resetMin);
    }
    if (message.resetMax !== 0) {
      writer.uint32(16).int64(message.resetMax);
    }
    for (const v of message.items) {
      Item.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Config {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.resetMin = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.resetMax = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.items.push(Item.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Config {
    return {
      $type: Config.$type,
      resetMin: isSet(object.resetMin)
        ? globalThis.Number(object.resetMin)
        : isSet(object.reset_min)
        ? globalThis.Number(object.reset_min)
        : 0,
      resetMax: isSet(object.resetMax)
        ? globalThis.Number(object.resetMax)
        : isSet(object.reset_max)
        ? globalThis.Number(object.reset_max)
        : 0,
      items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => Item.fromJSON(e)) : [],
    };
  },

  toJSON(message: Config): unknown {
    const obj: any = {};
    if (message.resetMin !== 0) {
      obj.resetMin = Math.round(message.resetMin);
    }
    if (message.resetMax !== 0) {
      obj.resetMax = Math.round(message.resetMax);
    }
    if (message.items?.length) {
      obj.items = message.items.map((e) => Item.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<Config>): Config {
    return Config.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Config>): Config {
    const message = createBaseConfig();
    message.resetMin = object.resetMin ?? 0;
    message.resetMax = object.resetMax ?? 0;
    message.items = object.items?.map((e) => Item.fromPartial(e)) || [];
    return message;
  },
};

messageTypeRegistry.set(Config.$type, Config);

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
