// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: common/geodata/geodat.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { messageTypeRegistry } from "../../typeRegistry";

export const protobufPackage = "xray.common.geodata";

export interface Domain {
  $type: "xray.common.geodata.Domain";
  /** Domain matching type. */
  type: Domain_Type;
  /** Domain value. */
  value: string;
  /** Attributes of this domain. May be used for filtering. */
  attribute: Domain_Attribute[];
}

/** Type of domain value. */
export enum Domain_Type {
  /** Substr - The value is used as a sub string. */
  Substr = 0,
  /** Regex - The value is used as a regular expression. */
  Regex = 1,
  /** Domain - The value is a domain. */
  Domain = 2,
  /** Full - The value is a full domain. */
  Full = 3,
  UNRECOGNIZED = -1,
}

export function domain_TypeFromJSON(object: any): Domain_Type {
  switch (object) {
    case 0:
    case "Substr":
      return Domain_Type.Substr;
    case 1:
    case "Regex":
      return Domain_Type.Regex;
    case 2:
    case "Domain":
      return Domain_Type.Domain;
    case 3:
    case "Full":
      return Domain_Type.Full;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Domain_Type.UNRECOGNIZED;
  }
}

export function domain_TypeToJSON(object: Domain_Type): string {
  switch (object) {
    case Domain_Type.Substr:
      return "Substr";
    case Domain_Type.Regex:
      return "Regex";
    case Domain_Type.Domain:
      return "Domain";
    case Domain_Type.Full:
      return "Full";
    case Domain_Type.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Domain_Attribute {
  $type: "xray.common.geodata.Domain.Attribute";
  key: string;
  boolValue?: boolean | undefined;
  intValue?: number | undefined;
}

export interface GeoSite {
  $type: "xray.common.geodata.GeoSite";
  code: string;
  domain: Domain[];
}

export interface GeoSiteList {
  $type: "xray.common.geodata.GeoSiteList";
  entry: GeoSite[];
}

export interface GeoSiteRule {
  $type: "xray.common.geodata.GeoSiteRule";
  file: string;
  code: string;
  attrs: string;
}

export interface DomainRule {
  $type: "xray.common.geodata.DomainRule";
  geosite?: GeoSiteRule | undefined;
  custom?: Domain | undefined;
}

export interface CIDR {
  $type: "xray.common.geodata.CIDR";
  /** IP address, should be either 4 or 16 bytes. */
  ip: Uint8Array;
  /** Number of leading ones in the network mask. */
  prefix: number;
}

export interface CIDRRule {
  $type: "xray.common.geodata.CIDRRule";
  cidr: CIDR | undefined;
  reverseMatch: boolean;
}

export interface GeoIP {
  $type: "xray.common.geodata.GeoIP";
  code: string;
  cidr: CIDR[];
  reverseMatch: boolean;
}

export interface GeoIPList {
  $type: "xray.common.geodata.GeoIPList";
  entry: GeoIP[];
}

export interface GeoIPRule {
  $type: "xray.common.geodata.GeoIPRule";
  file: string;
  code: string;
  reverseMatch: boolean;
}

export interface IPRule {
  $type: "xray.common.geodata.IPRule";
  geoip?: GeoIPRule | undefined;
  custom?: CIDRRule | undefined;
}

function createBaseDomain(): Domain {
  return { $type: "xray.common.geodata.Domain", type: 0, value: "", attribute: [] };
}

export const Domain: MessageFns<Domain, "xray.common.geodata.Domain"> = {
  $type: "xray.common.geodata.Domain" as const,

  encode(message: Domain, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    for (const v of message.attribute) {
      Domain_Attribute.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Domain {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDomain();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.attribute.push(Domain_Attribute.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Domain {
    return {
      $type: Domain.$type,
      type: isSet(object.type) ? domain_TypeFromJSON(object.type) : 0,
      value: isSet(object.value) ? globalThis.String(object.value) : "",
      attribute: globalThis.Array.isArray(object?.attribute)
        ? object.attribute.map((e: any) => Domain_Attribute.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Domain): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = domain_TypeToJSON(message.type);
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    if (message.attribute?.length) {
      obj.attribute = message.attribute.map((e) => Domain_Attribute.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<Domain>): Domain {
    return Domain.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Domain>): Domain {
    const message = createBaseDomain();
    message.type = object.type ?? 0;
    message.value = object.value ?? "";
    message.attribute = object.attribute?.map((e) => Domain_Attribute.fromPartial(e)) || [];
    return message;
  },
};

messageTypeRegistry.set(Domain.$type, Domain);

function createBaseDomain_Attribute(): Domain_Attribute {
  return { $type: "xray.common.geodata.Domain.Attribute", key: "", boolValue: undefined, intValue: undefined };
}

export const Domain_Attribute: MessageFns<Domain_Attribute, "xray.common.geodata.Domain.Attribute"> = {
  $type: "xray.common.geodata.Domain.Attribute" as const,

  encode(message: Domain_Attribute, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.boolValue !== undefined) {
      writer.uint32(16).bool(message.boolValue);
    }
    if (message.intValue !== undefined) {
      writer.uint32(24).int64(message.intValue);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Domain_Attribute {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDomain_Attribute();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.boolValue = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.intValue = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Domain_Attribute {
    return {
      $type: Domain_Attribute.$type,
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      boolValue: isSet(object.boolValue)
        ? globalThis.Boolean(object.boolValue)
        : isSet(object.bool_value)
        ? globalThis.Boolean(object.bool_value)
        : undefined,
      intValue: isSet(object.intValue)
        ? globalThis.Number(object.intValue)
        : isSet(object.int_value)
        ? globalThis.Number(object.int_value)
        : undefined,
    };
  },

  toJSON(message: Domain_Attribute): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.boolValue !== undefined) {
      obj.boolValue = message.boolValue;
    }
    if (message.intValue !== undefined) {
      obj.intValue = Math.round(message.intValue);
    }
    return obj;
  },

  create(base?: DeepPartial<Domain_Attribute>): Domain_Attribute {
    return Domain_Attribute.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Domain_Attribute>): Domain_Attribute {
    const message = createBaseDomain_Attribute();
    message.key = object.key ?? "";
    message.boolValue = object.boolValue ?? undefined;
    message.intValue = object.intValue ?? undefined;
    return message;
  },
};

messageTypeRegistry.set(Domain_Attribute.$type, Domain_Attribute);

function createBaseGeoSite(): GeoSite {
  return { $type: "xray.common.geodata.GeoSite", code: "", domain: [] };
}

export const GeoSite: MessageFns<GeoSite, "xray.common.geodata.GeoSite"> = {
  $type: "xray.common.geodata.GeoSite" as const,

  encode(message: GeoSite, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    for (const v of message.domain) {
      Domain.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GeoSite {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGeoSite();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.domain.push(Domain.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GeoSite {
    return {
      $type: GeoSite.$type,
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      domain: globalThis.Array.isArray(object?.domain) ? object.domain.map((e: any) => Domain.fromJSON(e)) : [],
    };
  },

  toJSON(message: GeoSite): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.domain?.length) {
      obj.domain = message.domain.map((e) => Domain.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<GeoSite>): GeoSite {
    return GeoSite.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GeoSite>): GeoSite {
    const message = createBaseGeoSite();
    message.code = object.code ?? "";
    message.domain = object.domain?.map((e) => Domain.fromPartial(e)) || [];
    return message;
  },
};

messageTypeRegistry.set(GeoSite.$type, GeoSite);

function createBaseGeoSiteList(): GeoSiteList {
  return { $type: "xray.common.geodata.GeoSiteList", entry: [] };
}

export const GeoSiteList: MessageFns<GeoSiteList, "xray.common.geodata.GeoSiteList"> = {
  $type: "xray.common.geodata.GeoSiteList" as const,

  encode(message: GeoSiteList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.entry) {
      GeoSite.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GeoSiteList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGeoSiteList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entry.push(GeoSite.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GeoSiteList {
    return {
      $type: GeoSiteList.$type,
      entry: globalThis.Array.isArray(object?.entry) ? object.entry.map((e: any) => GeoSite.fromJSON(e)) : [],
    };
  },

  toJSON(message: GeoSiteList): unknown {
    const obj: any = {};
    if (message.entry?.length) {
      obj.entry = message.entry.map((e) => GeoSite.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<GeoSiteList>): GeoSiteList {
    return GeoSiteList.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GeoSiteList>): GeoSiteList {
    const message = createBaseGeoSiteList();
    message.entry = object.entry?.map((e) => GeoSite.fromPartial(e)) || [];
    return message;
  },
};

messageTypeRegistry.set(GeoSiteList.$type, GeoSiteList);

function createBaseGeoSiteRule(): GeoSiteRule {
  return { $type: "xray.common.geodata.GeoSiteRule", file: "", code: "", attrs: "" };
}

export const GeoSiteRule: MessageFns<GeoSiteRule, "xray.common.geodata.GeoSiteRule"> = {
  $type: "xray.common.geodata.GeoSiteRule" as const,

  encode(message: GeoSiteRule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.file !== "") {
      writer.uint32(10).string(message.file);
    }
    if (message.code !== "") {
      writer.uint32(18).string(message.code);
    }
    if (message.attrs !== "") {
      writer.uint32(26).string(message.attrs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GeoSiteRule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGeoSiteRule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.attrs = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GeoSiteRule {
    return {
      $type: GeoSiteRule.$type,
      file: isSet(object.file) ? globalThis.String(object.file) : "",
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      attrs: isSet(object.attrs) ? globalThis.String(object.attrs) : "",
    };
  },

  toJSON(message: GeoSiteRule): unknown {
    const obj: any = {};
    if (message.file !== "") {
      obj.file = message.file;
    }
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.attrs !== "") {
      obj.attrs = message.attrs;
    }
    return obj;
  },

  create(base?: DeepPartial<GeoSiteRule>): GeoSiteRule {
    return GeoSiteRule.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GeoSiteRule>): GeoSiteRule {
    const message = createBaseGeoSiteRule();
    message.file = object.file ?? "";
    message.code = object.code ?? "";
    message.attrs = object.attrs ?? "";
    return message;
  },
};

messageTypeRegistry.set(GeoSiteRule.$type, GeoSiteRule);

function createBaseDomainRule(): DomainRule {
  return { $type: "xray.common.geodata.DomainRule", geosite: undefined, custom: undefined };
}

export const DomainRule: MessageFns<DomainRule, "xray.common.geodata.DomainRule"> = {
  $type: "xray.common.geodata.DomainRule" as const,

  encode(message: DomainRule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.geosite !== undefined) {
      GeoSiteRule.encode(message.geosite, writer.uint32(10).fork()).join();
    }
    if (message.custom !== undefined) {
      Domain.encode(message.custom, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DomainRule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDomainRule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.geosite = GeoSiteRule.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.custom = Domain.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DomainRule {
    return {
      $type: DomainRule.$type,
      geosite: isSet(object.geosite) ? GeoSiteRule.fromJSON(object.geosite) : undefined,
      custom: isSet(object.custom) ? Domain.fromJSON(object.custom) : undefined,
    };
  },

  toJSON(message: DomainRule): unknown {
    const obj: any = {};
    if (message.geosite !== undefined) {
      obj.geosite = GeoSiteRule.toJSON(message.geosite);
    }
    if (message.custom !== undefined) {
      obj.custom = Domain.toJSON(message.custom);
    }
    return obj;
  },

  create(base?: DeepPartial<DomainRule>): DomainRule {
    return DomainRule.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DomainRule>): DomainRule {
    const message = createBaseDomainRule();
    message.geosite = (object.geosite !== undefined && object.geosite !== null)
      ? GeoSiteRule.fromPartial(object.geosite)
      : undefined;
    message.custom = (object.custom !== undefined && object.custom !== null)
      ? Domain.fromPartial(object.custom)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(DomainRule.$type, DomainRule);

function createBaseCIDR(): CIDR {
  return { $type: "xray.common.geodata.CIDR", ip: new Uint8Array(0), prefix: 0 };
}

export const CIDR: MessageFns<CIDR, "xray.common.geodata.CIDR"> = {
  $type: "xray.common.geodata.CIDR" as const,

  encode(message: CIDR, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ip.length !== 0) {
      writer.uint32(10).bytes(message.ip);
    }
    if (message.prefix !== 0) {
      writer.uint32(16).uint32(message.prefix);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CIDR {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCIDR();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ip = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.prefix = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CIDR {
    return {
      $type: CIDR.$type,
      ip: isSet(object.ip) ? bytesFromBase64(object.ip) : new Uint8Array(0),
      prefix: isSet(object.prefix) ? globalThis.Number(object.prefix) : 0,
    };
  },

  toJSON(message: CIDR): unknown {
    const obj: any = {};
    if (message.ip.length !== 0) {
      obj.ip = base64FromBytes(message.ip);
    }
    if (message.prefix !== 0) {
      obj.prefix = Math.round(message.prefix);
    }
    return obj;
  },

  create(base?: DeepPartial<CIDR>): CIDR {
    return CIDR.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CIDR>): CIDR {
    const message = createBaseCIDR();
    message.ip = object.ip ?? new Uint8Array(0);
    message.prefix = object.prefix ?? 0;
    return message;
  },
};

messageTypeRegistry.set(CIDR.$type, CIDR);

function createBaseCIDRRule(): CIDRRule {
  return { $type: "xray.common.geodata.CIDRRule", cidr: undefined, reverseMatch: false };
}

export const CIDRRule: MessageFns<CIDRRule, "xray.common.geodata.CIDRRule"> = {
  $type: "xray.common.geodata.CIDRRule" as const,

  encode(message: CIDRRule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cidr !== undefined) {
      CIDR.encode(message.cidr, writer.uint32(10).fork()).join();
    }
    if (message.reverseMatch !== false) {
      writer.uint32(16).bool(message.reverseMatch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CIDRRule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCIDRRule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cidr = CIDR.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.reverseMatch = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CIDRRule {
    return {
      $type: CIDRRule.$type,
      cidr: isSet(object.cidr) ? CIDR.fromJSON(object.cidr) : undefined,
      reverseMatch: isSet(object.reverseMatch)
        ? globalThis.Boolean(object.reverseMatch)
        : isSet(object.reverse_match)
        ? globalThis.Boolean(object.reverse_match)
        : false,
    };
  },

  toJSON(message: CIDRRule): unknown {
    const obj: any = {};
    if (message.cidr !== undefined) {
      obj.cidr = CIDR.toJSON(message.cidr);
    }
    if (message.reverseMatch !== false) {
      obj.reverseMatch = message.reverseMatch;
    }
    return obj;
  },

  create(base?: DeepPartial<CIDRRule>): CIDRRule {
    return CIDRRule.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CIDRRule>): CIDRRule {
    const message = createBaseCIDRRule();
    message.cidr = (object.cidr !== undefined && object.cidr !== null) ? CIDR.fromPartial(object.cidr) : undefined;
    message.reverseMatch = object.reverseMatch ?? false;
    return message;
  },
};

messageTypeRegistry.set(CIDRRule.$type, CIDRRule);

function createBaseGeoIP(): GeoIP {
  return { $type: "xray.common.geodata.GeoIP", code: "", cidr: [], reverseMatch: false };
}

export const GeoIP: MessageFns<GeoIP, "xray.common.geodata.GeoIP"> = {
  $type: "xray.common.geodata.GeoIP" as const,

  encode(message: GeoIP, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    for (const v of message.cidr) {
      CIDR.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.reverseMatch !== false) {
      writer.uint32(24).bool(message.reverseMatch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GeoIP {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGeoIP();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cidr.push(CIDR.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.reverseMatch = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GeoIP {
    return {
      $type: GeoIP.$type,
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      cidr: globalThis.Array.isArray(object?.cidr) ? object.cidr.map((e: any) => CIDR.fromJSON(e)) : [],
      reverseMatch: isSet(object.reverseMatch)
        ? globalThis.Boolean(object.reverseMatch)
        : isSet(object.reverse_match)
        ? globalThis.Boolean(object.reverse_match)
        : false,
    };
  },

  toJSON(message: GeoIP): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.cidr?.length) {
      obj.cidr = message.cidr.map((e) => CIDR.toJSON(e));
    }
    if (message.reverseMatch !== false) {
      obj.reverseMatch = message.reverseMatch;
    }
    return obj;
  },

  create(base?: DeepPartial<GeoIP>): GeoIP {
    return GeoIP.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GeoIP>): GeoIP {
    const message = createBaseGeoIP();
    message.code = object.code ?? "";
    message.cidr = object.cidr?.map((e) => CIDR.fromPartial(e)) || [];
    message.reverseMatch = object.reverseMatch ?? false;
    return message;
  },
};

messageTypeRegistry.set(GeoIP.$type, GeoIP);

function createBaseGeoIPList(): GeoIPList {
  return { $type: "xray.common.geodata.GeoIPList", entry: [] };
}

export const GeoIPList: MessageFns<GeoIPList, "xray.common.geodata.GeoIPList"> = {
  $type: "xray.common.geodata.GeoIPList" as const,

  encode(message: GeoIPList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.entry) {
      GeoIP.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GeoIPList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGeoIPList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entry.push(GeoIP.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GeoIPList {
    return {
      $type: GeoIPList.$type,
      entry: globalThis.Array.isArray(object?.entry) ? object.entry.map((e: any) => GeoIP.fromJSON(e)) : [],
    };
  },

  toJSON(message: GeoIPList): unknown {
    const obj: any = {};
    if (message.entry?.length) {
      obj.entry = message.entry.map((e) => GeoIP.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<GeoIPList>): GeoIPList {
    return GeoIPList.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GeoIPList>): GeoIPList {
    const message = createBaseGeoIPList();
    message.entry = object.entry?.map((e) => GeoIP.fromPartial(e)) || [];
    return message;
  },
};

messageTypeRegistry.set(GeoIPList.$type, GeoIPList);

function createBaseGeoIPRule(): GeoIPRule {
  return { $type: "xray.common.geodata.GeoIPRule", file: "", code: "", reverseMatch: false };
}

export const GeoIPRule: MessageFns<GeoIPRule, "xray.common.geodata.GeoIPRule"> = {
  $type: "xray.common.geodata.GeoIPRule" as const,

  encode(message: GeoIPRule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.file !== "") {
      writer.uint32(10).string(message.file);
    }
    if (message.code !== "") {
      writer.uint32(18).string(message.code);
    }
    if (message.reverseMatch !== false) {
      writer.uint32(24).bool(message.reverseMatch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GeoIPRule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGeoIPRule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.reverseMatch = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GeoIPRule {
    return {
      $type: GeoIPRule.$type,
      file: isSet(object.file) ? globalThis.String(object.file) : "",
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      reverseMatch: isSet(object.reverseMatch)
        ? globalThis.Boolean(object.reverseMatch)
        : isSet(object.reverse_match)
        ? globalThis.Boolean(object.reverse_match)
        : false,
    };
  },

  toJSON(message: GeoIPRule): unknown {
    const obj: any = {};
    if (message.file !== "") {
      obj.file = message.file;
    }
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.reverseMatch !== false) {
      obj.reverseMatch = message.reverseMatch;
    }
    return obj;
  },

  create(base?: DeepPartial<GeoIPRule>): GeoIPRule {
    return GeoIPRule.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GeoIPRule>): GeoIPRule {
    const message = createBaseGeoIPRule();
    message.file = object.file ?? "";
    message.code = object.code ?? "";
    message.reverseMatch = object.reverseMatch ?? false;
    return message;
  },
};

messageTypeRegistry.set(GeoIPRule.$type, GeoIPRule);

function createBaseIPRule(): IPRule {
  return { $type: "xray.common.geodata.IPRule", geoip: undefined, custom: undefined };
}

export const IPRule: MessageFns<IPRule, "xray.common.geodata.IPRule"> = {
  $type: "xray.common.geodata.IPRule" as const,

  encode(message: IPRule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.geoip !== undefined) {
      GeoIPRule.encode(message.geoip, writer.uint32(10).fork()).join();
    }
    if (message.custom !== undefined) {
      CIDRRule.encode(message.custom, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IPRule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIPRule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.geoip = GeoIPRule.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.custom = CIDRRule.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IPRule {
    return {
      $type: IPRule.$type,
      geoip: isSet(object.geoip) ? GeoIPRule.fromJSON(object.geoip) : undefined,
      custom: isSet(object.custom) ? CIDRRule.fromJSON(object.custom) : undefined,
    };
  },

  toJSON(message: IPRule): unknown {
    const obj: any = {};
    if (message.geoip !== undefined) {
      obj.geoip = GeoIPRule.toJSON(message.geoip);
    }
    if (message.custom !== undefined) {
      obj.custom = CIDRRule.toJSON(message.custom);
    }
    return obj;
  },

  create(base?: DeepPartial<IPRule>): IPRule {
    return IPRule.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<IPRule>): IPRule {
    const message = createBaseIPRule();
    message.geoip = (object.geoip !== undefined && object.geoip !== null)
      ? GeoIPRule.fromPartial(object.geoip)
      : undefined;
    message.custom = (object.custom !== undefined && object.custom !== null)
      ? CIDRRule.fromPartial(object.custom)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(IPRule.$type, IPRule);

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
