// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v5.29.3
// source: common/net/address.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { messageTypeRegistry } from "../../typeRegistry";

export const protobufPackage = "xray.common.net";

/**
 * Address of a network host. It may be either an IP address or a domain
 * address.
 */
export interface IPOrDomain {
  $type: "xray.common.net.IPOrDomain";
  /** IP address. Must by either 4 or 16 bytes. */
  ip?:
    | Uint8Array
    | undefined;
  /** Domain address. */
  domain?: string | undefined;
}

function createBaseIPOrDomain(): IPOrDomain {
  return { $type: "xray.common.net.IPOrDomain", ip: undefined, domain: undefined };
}

export const IPOrDomain: MessageFns<IPOrDomain, "xray.common.net.IPOrDomain"> = {
  $type: "xray.common.net.IPOrDomain" as const,

  encode(message: IPOrDomain, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ip !== undefined) {
      writer.uint32(10).bytes(message.ip);
    }
    if (message.domain !== undefined) {
      writer.uint32(18).string(message.domain);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IPOrDomain {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIPOrDomain();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ip = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IPOrDomain {
    return {
      $type: IPOrDomain.$type,
      ip: isSet(object.ip) ? bytesFromBase64(object.ip) : undefined,
      domain: isSet(object.domain) ? globalThis.String(object.domain) : undefined,
    };
  },

  toJSON(message: IPOrDomain): unknown {
    const obj: any = {};
    if (message.ip !== undefined) {
      obj.ip = base64FromBytes(message.ip);
    }
    if (message.domain !== undefined) {
      obj.domain = message.domain;
    }
    return obj;
  },

  create(base?: DeepPartial<IPOrDomain>): IPOrDomain {
    return IPOrDomain.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<IPOrDomain>): IPOrDomain {
    const message = createBaseIPOrDomain();
    message.ip = object.ip ?? undefined;
    message.domain = object.domain ?? undefined;
    return message;
  },
};

messageTypeRegistry.set(IPOrDomain.$type, IPOrDomain);

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
