// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v5.29.3
// source: proxy/blackhole/config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { TypedMessage } from "../../common/serial/typed_message";
import { messageTypeRegistry } from "../../typeRegistry";

export const protobufPackage = "xray.proxy.blackhole";

export interface NoneResponse {
  $type: "xray.proxy.blackhole.NoneResponse";
}

export interface HTTPResponse {
  $type: "xray.proxy.blackhole.HTTPResponse";
}

export interface Config {
  $type: "xray.proxy.blackhole.Config";
  response: TypedMessage | undefined;
}

function createBaseNoneResponse(): NoneResponse {
  return { $type: "xray.proxy.blackhole.NoneResponse" };
}

export const NoneResponse: MessageFns<NoneResponse, "xray.proxy.blackhole.NoneResponse"> = {
  $type: "xray.proxy.blackhole.NoneResponse" as const,

  encode(_: NoneResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NoneResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNoneResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): NoneResponse {
    return { $type: NoneResponse.$type };
  },

  toJSON(_: NoneResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<NoneResponse>): NoneResponse {
    return NoneResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<NoneResponse>): NoneResponse {
    const message = createBaseNoneResponse();
    return message;
  },
};

messageTypeRegistry.set(NoneResponse.$type, NoneResponse);

function createBaseHTTPResponse(): HTTPResponse {
  return { $type: "xray.proxy.blackhole.HTTPResponse" };
}

export const HTTPResponse: MessageFns<HTTPResponse, "xray.proxy.blackhole.HTTPResponse"> = {
  $type: "xray.proxy.blackhole.HTTPResponse" as const,

  encode(_: HTTPResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HTTPResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHTTPResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): HTTPResponse {
    return { $type: HTTPResponse.$type };
  },

  toJSON(_: HTTPResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<HTTPResponse>): HTTPResponse {
    return HTTPResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<HTTPResponse>): HTTPResponse {
    const message = createBaseHTTPResponse();
    return message;
  },
};

messageTypeRegistry.set(HTTPResponse.$type, HTTPResponse);

function createBaseConfig(): Config {
  return { $type: "xray.proxy.blackhole.Config", response: undefined };
}

export const Config: MessageFns<Config, "xray.proxy.blackhole.Config"> = {
  $type: "xray.proxy.blackhole.Config" as const,

  encode(message: Config, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.response !== undefined) {
      TypedMessage.encode(message.response, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Config {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.response = TypedMessage.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Config {
    return {
      $type: Config.$type,
      response: isSet(object.response) ? TypedMessage.fromJSON(object.response) : undefined,
    };
  },

  toJSON(message: Config): unknown {
    const obj: any = {};
    if (message.response !== undefined) {
      obj.response = TypedMessage.toJSON(message.response);
    }
    return obj;
  },

  create(base?: DeepPartial<Config>): Config {
    return Config.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Config>): Config {
    const message = createBaseConfig();
    message.response = (object.response !== undefined && object.response !== null)
      ? TypedMessage.fromPartial(object.response)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(Config.$type, Config);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
