// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: proxy/hysteria/config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ServerEndpoint } from "../../common/protocol/server_spec";
import { User } from "../../common/protocol/user";
import { messageTypeRegistry } from "../../typeRegistry";

export const protobufPackage = "xray.proxy.hysteria";

export interface ClientConfig {
  $type: "xray.proxy.hysteria.ClientConfig";
  version: number;
  server: ServerEndpoint | undefined;
}

export interface ServerConfig {
  $type: "xray.proxy.hysteria.ServerConfig";
  users: User[];
}

function createBaseClientConfig(): ClientConfig {
  return { $type: "xray.proxy.hysteria.ClientConfig", version: 0, server: undefined };
}

export const ClientConfig: MessageFns<ClientConfig, "xray.proxy.hysteria.ClientConfig"> = {
  $type: "xray.proxy.hysteria.ClientConfig" as const,

  encode(message: ClientConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version !== 0) {
      writer.uint32(8).int32(message.version);
    }
    if (message.server !== undefined) {
      ServerEndpoint.encode(message.server, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClientConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClientConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.version = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.server = ServerEndpoint.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClientConfig {
    return {
      $type: ClientConfig.$type,
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      server: isSet(object.server) ? ServerEndpoint.fromJSON(object.server) : undefined,
    };
  },

  toJSON(message: ClientConfig): unknown {
    const obj: any = {};
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.server !== undefined) {
      obj.server = ServerEndpoint.toJSON(message.server);
    }
    return obj;
  },

  create(base?: DeepPartial<ClientConfig>): ClientConfig {
    return ClientConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ClientConfig>): ClientConfig {
    const message = createBaseClientConfig();
    message.version = object.version ?? 0;
    message.server = (object.server !== undefined && object.server !== null)
      ? ServerEndpoint.fromPartial(object.server)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(ClientConfig.$type, ClientConfig);

function createBaseServerConfig(): ServerConfig {
  return { $type: "xray.proxy.hysteria.ServerConfig", users: [] };
}

export const ServerConfig: MessageFns<ServerConfig, "xray.proxy.hysteria.ServerConfig"> = {
  $type: "xray.proxy.hysteria.ServerConfig" as const,

  encode(message: ServerConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.users) {
      User.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.users.push(User.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerConfig {
    return {
      $type: ServerConfig.$type,
      users: globalThis.Array.isArray(object?.users) ? object.users.map((e: any) => User.fromJSON(e)) : [],
    };
  },

  toJSON(message: ServerConfig): unknown {
    const obj: any = {};
    if (message.users?.length) {
      obj.users = message.users.map((e) => User.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ServerConfig>): ServerConfig {
    return ServerConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ServerConfig>): ServerConfig {
    const message = createBaseServerConfig();
    message.users = object.users?.map((e) => User.fromPartial(e)) || [];
    return message;
  },
};

messageTypeRegistry.set(ServerConfig.$type, ServerConfig);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
