// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.7
//   protoc               v5.28.3
// source: transport/internet/headers/wechat/config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { messageTypeRegistry } from "../../../../typeRegistry";

export const protobufPackage = "xray.transport.internet.headers.wechat";

export interface VideoConfig {
  $type: "xray.transport.internet.headers.wechat.VideoConfig";
}

function createBaseVideoConfig(): VideoConfig {
  return { $type: "xray.transport.internet.headers.wechat.VideoConfig" };
}

export const VideoConfig: MessageFns<VideoConfig, "xray.transport.internet.headers.wechat.VideoConfig"> = {
  $type: "xray.transport.internet.headers.wechat.VideoConfig" as const,

  encode(_: VideoConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VideoConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVideoConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): VideoConfig {
    return { $type: VideoConfig.$type };
  },

  toJSON(_: VideoConfig): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<VideoConfig>): VideoConfig {
    return VideoConfig.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<VideoConfig>): VideoConfig {
    const message = createBaseVideoConfig();
    return message;
  },
};

messageTypeRegistry.set(VideoConfig.$type, VideoConfig);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
