// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: transport/internet/kcp/config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { messageTypeRegistry } from "../../../typeRegistry";

export const protobufPackage = "xray.transport.internet.kcp";

export interface Config {
  $type: "xray.transport.internet.kcp.Config";
  mtu: number;
  tti: number;
  uplinkCapacity: number;
  downlinkCapacity: number;
  cwndMultiplier: number;
  maxSendingWindow: number;
}

function createBaseConfig(): Config {
  return {
    $type: "xray.transport.internet.kcp.Config",
    mtu: 0,
    tti: 0,
    uplinkCapacity: 0,
    downlinkCapacity: 0,
    cwndMultiplier: 0,
    maxSendingWindow: 0,
  };
}

export const Config: MessageFns<Config, "xray.transport.internet.kcp.Config"> = {
  $type: "xray.transport.internet.kcp.Config" as const,

  encode(message: Config, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mtu !== 0) {
      writer.uint32(8).uint32(message.mtu);
    }
    if (message.tti !== 0) {
      writer.uint32(16).uint32(message.tti);
    }
    if (message.uplinkCapacity !== 0) {
      writer.uint32(24).uint32(message.uplinkCapacity);
    }
    if (message.downlinkCapacity !== 0) {
      writer.uint32(32).uint32(message.downlinkCapacity);
    }
    if (message.cwndMultiplier !== 0) {
      writer.uint32(40).uint32(message.cwndMultiplier);
    }
    if (message.maxSendingWindow !== 0) {
      writer.uint32(48).uint32(message.maxSendingWindow);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Config {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.mtu = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.tti = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.uplinkCapacity = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.downlinkCapacity = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.cwndMultiplier = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.maxSendingWindow = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Config {
    return {
      $type: Config.$type,
      mtu: isSet(object.mtu) ? globalThis.Number(object.mtu) : 0,
      tti: isSet(object.tti) ? globalThis.Number(object.tti) : 0,
      uplinkCapacity: isSet(object.uplinkCapacity)
        ? globalThis.Number(object.uplinkCapacity)
        : isSet(object.uplink_capacity)
        ? globalThis.Number(object.uplink_capacity)
        : 0,
      downlinkCapacity: isSet(object.downlinkCapacity)
        ? globalThis.Number(object.downlinkCapacity)
        : isSet(object.downlink_capacity)
        ? globalThis.Number(object.downlink_capacity)
        : 0,
      cwndMultiplier: isSet(object.cwndMultiplier)
        ? globalThis.Number(object.cwndMultiplier)
        : isSet(object.cwnd_multiplier)
        ? globalThis.Number(object.cwnd_multiplier)
        : 0,
      maxSendingWindow: isSet(object.maxSendingWindow)
        ? globalThis.Number(object.maxSendingWindow)
        : isSet(object.max_sending_window)
        ? globalThis.Number(object.max_sending_window)
        : 0,
    };
  },

  toJSON(message: Config): unknown {
    const obj: any = {};
    if (message.mtu !== 0) {
      obj.mtu = Math.round(message.mtu);
    }
    if (message.tti !== 0) {
      obj.tti = Math.round(message.tti);
    }
    if (message.uplinkCapacity !== 0) {
      obj.uplinkCapacity = Math.round(message.uplinkCapacity);
    }
    if (message.downlinkCapacity !== 0) {
      obj.downlinkCapacity = Math.round(message.downlinkCapacity);
    }
    if (message.cwndMultiplier !== 0) {
      obj.cwndMultiplier = Math.round(message.cwndMultiplier);
    }
    if (message.maxSendingWindow !== 0) {
      obj.maxSendingWindow = Math.round(message.maxSendingWindow);
    }
    return obj;
  },

  create(base?: DeepPartial<Config>): Config {
    return Config.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Config>): Config {
    const message = createBaseConfig();
    message.mtu = object.mtu ?? 0;
    message.tti = object.tti ?? 0;
    message.uplinkCapacity = object.uplinkCapacity ?? 0;
    message.downlinkCapacity = object.downlinkCapacity ?? 0;
    message.cwndMultiplier = object.cwndMultiplier ?? 0;
    message.maxSendingWindow = object.maxSendingWindow ?? 0;
    return message;
  },
};

messageTypeRegistry.set(Config.$type, Config);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
