// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.7
//   protoc               v5.28.3
// source: common/protocol/headers.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { messageTypeRegistry } from "../../typeRegistry";

export const protobufPackage = "xray.common.protocol";

export enum SecurityType {
  UNKNOWN = 0,
  AUTO = 2,
  AES128_GCM = 3,
  CHACHA20_POLY1305 = 4,
  /** NONE - [DEPRECATED 2023-06] */
  NONE = 5,
  ZERO = 6,
  UNRECOGNIZED = -1,
}

export function securityTypeFromJSON(object: any): SecurityType {
  switch (object) {
    case 0:
    case "UNKNOWN":
      return SecurityType.UNKNOWN;
    case 2:
    case "AUTO":
      return SecurityType.AUTO;
    case 3:
    case "AES128_GCM":
      return SecurityType.AES128_GCM;
    case 4:
    case "CHACHA20_POLY1305":
      return SecurityType.CHACHA20_POLY1305;
    case 5:
    case "NONE":
      return SecurityType.NONE;
    case 6:
    case "ZERO":
      return SecurityType.ZERO;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SecurityType.UNRECOGNIZED;
  }
}

export function securityTypeToJSON(object: SecurityType): string {
  switch (object) {
    case SecurityType.UNKNOWN:
      return "UNKNOWN";
    case SecurityType.AUTO:
      return "AUTO";
    case SecurityType.AES128_GCM:
      return "AES128_GCM";
    case SecurityType.CHACHA20_POLY1305:
      return "CHACHA20_POLY1305";
    case SecurityType.NONE:
      return "NONE";
    case SecurityType.ZERO:
      return "ZERO";
    case SecurityType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface SecurityConfig {
  $type: "xray.common.protocol.SecurityConfig";
  type: SecurityType;
}

function createBaseSecurityConfig(): SecurityConfig {
  return { $type: "xray.common.protocol.SecurityConfig", type: 0 };
}

export const SecurityConfig: MessageFns<SecurityConfig, "xray.common.protocol.SecurityConfig"> = {
  $type: "xray.common.protocol.SecurityConfig" as const,

  encode(message: SecurityConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SecurityConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSecurityConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SecurityConfig {
    return { $type: SecurityConfig.$type, type: isSet(object.type) ? securityTypeFromJSON(object.type) : 0 };
  },

  toJSON(message: SecurityConfig): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = securityTypeToJSON(message.type);
    }
    return obj;
  },

  create(base?: DeepPartial<SecurityConfig>): SecurityConfig {
    return SecurityConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SecurityConfig>): SecurityConfig {
    const message = createBaseSecurityConfig();
    message.type = object.type ?? 0;
    return message;
  },
};

messageTypeRegistry.set(SecurityConfig.$type, SecurityConfig);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
